PIPELINE_NAME = "networksecurity"
ARTIFACT_DIR = "artifact"
FILE_NAME = "PhishingData.csv"

TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"

DATA_INGESTION_COLLECTION_NAME = "Network_Data"
DATA_INGESTION_DATABASE_NAME = "CyverSecurity"
DATA_INGESTION_DIR_NAME = "data_ingestion"
DATA_INGESTION_FEATURE_STORE_DIR = "feature_store"
DATA_INGESTION_INGESTED_DIR = "ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATION = 0.2

TARGET_COLUMN = "result"